### ISSUE TITLE
Corrupt JPEG data.

### ISSUE THREAD

**Issue by AssociationSirius** [serge-rgb/TinyJPEG#1]
With use of function tje_encode_to_file_at_quality:

	glReadPixels( (rw-rh)/2, 0, rh, rh, GL_RGB, GL_UNSIGNED_BYTE, pixels);
   	tje_encode_to_file_at_quality(filename.c_str(), 3,rh, rh, 3, pixels);

The Gimp say me:
Corrupt JPEG data: 26 extraneous bytes before marker 0xdb

![spacecrafter-00355](https://cloud.githubusercontent.com/assets/9870583/10646760/4e896574-7835-11e5-8774-88c318854d81.jpg)

**Comment by serge-rgb** [comment]
Which version of GIMP are you using? What OS? 

I can open it fine with GIMP 2.8.14 on Windows. However, there is definitely a bug in the header writing code right before writing the DB marker. That is probably why your version of Gimp is failing to open this image. If you tell me your Gimp Version and OS, I might be able to reproduce the bug and fix it.

I tried different programs and found that that Quicktime PictureViewer can't open tiny_jpeg files. Might be related.

**Comment by serge-rgb** [comment]
Update:

On a virtual machine running Linux Mint with Gimp 2.8.10 I am getting the same error message. I'll fix it later tonight. 
Thanks for the report

**Comment by serge-rgb** [comment]
The previous two commits (e2f5ea0 and 687d6de) stop The Gimp from complaining.

Two bugs with one stone. =) Thanks again for reporting the issue.
