### ISSUE TITLE
comment without  tag

### ISSUE THREAD

**Issue by AssociationSirius** [serge-rgb/TinyJPEG#4]
line 1127

there is a problem with a comment who is not declared as comment

**Comment by serge-rgb** [comment]
Apologies for this one. It was sloppy of me.
Please let me know if tiny jpeg is working for you. I'm interested in your project. You might be the first user of the library who I don't know directly :)

**Comment by AssociationSirius** [comment]
Good evening,

I am a French programmer, my english is bad, sorry ! I develop in C ++/OpenGL a planetarium software. I use it in a 6m diameter dome to recreate 360 ° around and above 180 ° me a star-filled sky. You have see a exemple )

My app allows you to make screenshots and capture frames from frames to make videos. And to make screen backups, I needed a simple JPG file, easy to implement and clean.

Bingo! Tiny_Jpeg.h exist!

It is for me to thank you for your work. Really.

I shared your work with friends and believe me, your library is used by two other students because it's SIMPLE !!!


 

The world is big, crazy often sad.

But there are people like you that advance the work of other strangers like me.

You are awesome. Realy.

Thanks again.

**Comment by serge-rgb** [comment]
Thank you so much for the nice words =) You made my day and probably my weekend too. I wish I had more words. =) *Hug*
