### ISSUE TITLE
Special request

### ISSUE THREAD

**Issue by AssociationSirius** [serge-rgb/TinyJPEG#9]
I'm sorry to ask for that again but with the time that has passed, I'm unable to manipulate your source code to save an image from the OpenGL buffer to avoid symmetry of the image.

You gave me an indication but I forgot!

The problem is that in OpenGL I get this image while I should get the image by vertical mirror.

![spacecrafter-17 03 05-08 00 13](https://cloud.githubusercontent.com/assets/9870583/23585263/f19f646a-0179-11e7-8abc-41429f155d42.jpg)

Thanks again for everything.
Sorry to ask the same question twice!

**Comment by serge-rgb** [comment]
Hi there,

Here is a link to the issue you mentioned: https://github.com/serge-rgb/TinyJPEG/issues/3

You can look at the version of tiny_jpeg that I put there: https://gist.github.com/serge-rgb/61248241d2197e3d98c1
In lines 1030 to 1050 there are some commented lines that show the changes I made.

Let me know if this works for you!

**Comment by AssociationSirius** [comment]
Hi Serge,

Thanks. With your indications, I found the way to save images in OpenGL at the right position.
It works properly. Your library is doing exactly what I needed. Thanks for all.
